[build] 
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  HUGO_BASEURL = "/"

## add password protection during developing phase
# https://developer.aliyun.com/mirror/npm/package/netlify-plugin-password-protection
[[plugins]]
  package = "netlify-plugin-password-protection"